name: Fidelity tests

on: pull_request

jobs:
  compare_renders:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: NPM install
      run: npm ci

    # - name: Lint TypeScript sources
    #   run: npm run lint

    - name: Build packages
      run: |
       npm run build --workspace=@google/model-viewer --workspace=@google/model-viewer-render-fidelity-tools

    - name: Fidelity tests
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: npm run test --workspace=@google/model-viewer-render-fidelity-tools
